<div class="main">
<input type="hidden" class="checkStoreId" value="7136"><div class="ma-banner"><div class="container"><div class="container-inner"></div></div></div><div class="main-container col2-left-layout"><div class="container"><div class="container-inner"><div class="main"><div class="breadcrumbs"><ol class="breadcrumb"><li>
<a href="/">Trang chủ</a></li><li>
<a href="">Thanh toán</a></li></ol></div><div class="main-inner"><div class="row" id="info-cart"><div class="col-main col-lg-12 col-md-12 col-sm-12 col-xs-12"><form action="" method="post" id="formCheckOut" class=""><div id="content"><h1 style="margin-bottom: 12px;font-size: 25px;">Thanh toán đơn hàng</h1><div class="checkout"><div id="payment-address"><div class="checkout-heading">
<span>Thông tin khách hàng</span></div><div class="checkout-content" style="display: block;"><div class="col-lg-5 col-md-5 col-sm-12 col-xs-12"><div id="c">
<div class="form-validation-field-0formError parentFormformCheckOut formError" style="opacity: 0.87; position: absolute; top: 10px; left: 410px; margin-top: -56px;"><div class="formErrorContent">* Trường này bắt buộc<br></div><div class="formErrorArrow"><div class="line10"><!-- --></div><div class="line9"><!-- --></div><div class="line8"><!-- --></div><div class="line7"><!-- --></div><div class="line6"><!-- --></div><div class="line5"><!-- --></div><div class="line4"><!-- --></div><div class="line3"><!-- --></div><div class="line2"><!-- --></div><div class="line1"><!-- --></div></div></div><input type="text" name="customerName" class="validate[required]" value="" placeholder="Họ và tên" id="form-validation-field-0"></div><div id="c">
<input type="text" name="customerMobile" class="validate[required]" value="" placeholder="Điện thoại"></div><div id="c">
<input type="text" name="customerEmail" class="validate[required]" value="" placeholder="Email"></div></div><div class="col-lg-1 col-md-1 col-sm-12 col-xs-12"></div><div class="col-lg-5 col-md-5 col-sm-12 col-xs-12"><div id="c">
<select id="cityId" name="customerCityId" class="validate[required]"><option value="">Thành phố</option><option value="2">Hà Nội</option><option value="3">Hồ Chí Minh</option><option value="4">An Giang</option><option value="5">Bà Rịa - Vũng Tàu</option><option value="6">Bắc Ninh</option><option value="7">Bắc Giang</option><option value="8">Bình Dương</option><option value="9">Bình Định</option><option value="10">Bình Phước</option><option value="11">Bình Thuận</option><option value="13">Bến Tre</option><option value="14">Bắc Cạn</option><option value="15">Cần Thơ</option><option value="17">Khánh Hòa</option><option value="19">Thừa Thiên Huế</option><option value="20">Lào Cai</option><option value="21">Quảng Ninh</option><option value="22">Đồng Nai</option><option value="23">Nam Định</option><option value="24">Cà Mau</option><option value="25">Cao Bằng</option><option value="26">Gia Lai</option><option value="27">Hà Giang</option><option value="28">Hà Nam</option><option value="30">Hà Tĩnh</option><option value="31">Hải Dương</option><option value="32">Hải Phòng</option><option value="33">Hoà Bình</option><option value="34">Hưng Yên</option><option value="35">Kiên Giang</option><option value="36">Kon Tum</option><option value="37">Lai Châu</option><option value="38">Lâm Đồng</option><option value="39">Lạng Sơn</option><option value="40">Long An</option><option value="41">Nghệ An</option><option value="42">Ninh Bình</option><option value="43">Ninh Thuận</option><option value="44">Phú Thọ</option><option value="45">Phú Yên</option><option value="46">Quảng Bình</option><option value="47">Quảng Nam</option><option value="48">Quảng Ngãi</option><option value="49">Quảng Trị</option><option value="50">Sóc Trăng</option><option value="51">Sơn La</option><option value="52">Tây Ninh</option><option value="53">Thái Bình</option><option value="54">Thái Nguyên</option><option value="55">Thanh Hoá</option><option value="56">Tiền Giang</option><option value="57">Trà Vinh</option><option value="58">Tuyên Quang</option><option value="59">Vĩnh Long</option><option value="60">Vĩnh Phúc</option><option value="61">Yên Bái</option><option value="62">Đắc Lắc</option><option value="64">Đồng Tháp</option><option value="65">Đà Nẵng</option><option value="67">Đắc Nông</option><option value="68">Hậu Giang</option><option value="70">Bạc Liêu</option><option value="71">Điện Biên</option>
</select></div><div id="c">
<select id="districtId" name="customerDistrictId" class="validate[required]"><option value="">Quận Huyện</option>
</select></div><div id="c">
<input type="text" name="customerAddress" class="validate[required]" value="" placeholder="Địa chỉ"></div></div><div class="col-lg-1 col-md-1 col-sm-12 col-xs-12"></div></div><div style="clear: both;padding: 7px"></div></div><div id="payment-address"><div class="checkout-heading">
<span>Hình thức thanh toán</span></div><div class="checkout-content" style="display: block;"><div id="paymentMethod"><div class="b">
<label>
<input type="radio" id="rdPaymentMethodCod" name="paymentMethod" class="validate[required]" value="1">
Thanh toán tại nhà                                                        </label></div><div class="b">
<label>
<input type="radio" name="paymentMethod" disabled="" class="validate[required]" value="3">
Bằng ví điện tử Bảo Kim                                                                    <i style="font-weight: normal;">(Đăng nhập để thực hiện chức năng này                                                                        )</i>
</label></div></div></div></div><div id="payment-address"><div class="checkout-heading">
<span>Thông tin đơn hàng</span></div><div class="checkout-content" style="display: block;"><div class="cart-info table-responsive"><table class="table checkoutTable"><thead class="hidden-phone thcheckout"><tr><td class="image">Ảnh</td><td class="name">Tên sản phẩm</td><td class="quantity">Số lượng</td><td class="price">Đơn giá</td><td class="total">Xóa</td><td class="total">Thành tiền</td></tr></thead><tbody><tr><td class="image" data-label="Ảnh" id="img-cart">
<a class="" href="/p8555927/thun-nam-088019wh">
<img src="//cdn.nhanh.vn/cdn/store/7136/ps/20180912/thun_nam_16000__1__500x750.jpg" alt="THUN NAM 088019WH" title="THUN NAM 088019WH">
</a></td><td class="name" data-label="Tên sản phẩm">
<a class="" href="/p8555927/thun-nam-088019wh">THUN NAM 088019WH</a></td><td class="quantity" data-label="Số lượng">1</td><td class="price" data-label="Giá">245,000                                                                        vnđ</td><td class="remove" data-label="Xóa">
<a style="display: block;text-align: center" class="remove-cart" href="javascript: void(0)" title="8555927"><i class="fa fa-trash-o" style="color: #333"></i></a></td><td class="total" data-label="Thành tiền">245,000                                                                        vnđ</td></tr><tr><td class="tdnone"><textarea style="display: none;" id="productShipfee">{"8555927":1}</textarea><input type="hidden" id="totalCartMoney" value="245000"></td><td class="tRight tdnone" colspan="4">Tổng đơn hàng</td><td data-label="" class="tRight tdnone">
<b>245,000                                                                    vnđ</b></td></tr><tr><td class="tRight tdnone" colspan="5">Phí vận chuyển</td><td data-label="" class="tRight tdnone"><b id="shipFee">0
vnđ</b></td></tr><tr><td class="tRight tdnone" colspan="5">Giảm giá</td><td data-label="" class="tRight tdnone"><b id="couponFee">0 vnđ</b></td></tr><tr><td class="tRight" colspan="5">Tổng tiền</td><td data-label="" class="tRight"><b id="showTotalMoney">245,000                                                                    vnđ</b></td></tr><tr><td class="tRight" colspan="5">Nhập mã giảm giá</td><td data-label="" class="tRight">
<input id="coupon" type="text" name="couponCode" style="height: 27px;width: 150px;border-radius: 0">
<button type="button" id="getCoupon" class="btnRed" style="padding: 5px 10px; border: 1px solid #ccc;font-weight: bold;">
Sử dụng</button></td></tr><tr><td class="tdnone"></td><td colspan="5" class="tRight tdnone">
<input type="hidden" id="baokimPmMethodId" name="baokimBankPaymentMethodId">
<button type="submit" class="btn button btnCheckout" style="border-radius:0;text-transform: uppercase;margin-top: 0;padding-left: 1% !important; ">Xác nhận</button></td></tr></tbody></table></div></div></div></div></div></form></div></div></div></div></div></div></div><div style="display: none"><div id="progressbar" style="text-align: center;">
<img src="/tp/cucre/img/loading.gif"><p style="font-weight:bold;">Đang xử lý...</p></div></div><style>.fancybox-inner {
        height: auto !important;
    }

    .ui-progressbar {
        height: 6em !important;
    }</style></div>